### ISSUE TITLE
Dipper Out of Memory

### ISSUE THREAD

**Issue by GregxmHu** [vinusankars/Reliability-of-AI-text-detectors#1]
I want to know your device utilization of the recursive paraphrase experiment with Dipper-XXL.

**Comment by GregxmHu** [comment]
That is, what device do you use? N*A100?

**Comment by vinusankars** [comment]
Hi! For DIPPER, we used RTX A6000.

**Comment by vinusankars** [comment]
Hi! For DIPPER, we used RTX A6000.

**Comment by GregxmHu** [comment]
How many A6000 you use?

**Comment by GregxmHu** [comment]
Can Dipper be loaded to 8 V100 GPUs which with 32G memory?
